-- Inserts de 100 estilos Manuais

-- MASCULINO - Estúdio
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 01/50', 'Estúdio', 'Força, sofisticação e mistério cinematográfico.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 02/50', 'Estúdio', 'Elegância corporativa e tom clássico de liderança.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 03/50', 'Estúdio', 'Acessibilidade e calor em uma composição harmoniosa e natural.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 04/50', 'Estúdio', 'Dinamismo, vitória e energia de sucesso.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 05/50', 'Estúdio', 'Intensidade e masculinidade artística moderna.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 06/50', 'Estúdio', 'Inteligência, confiança e apelo executivo.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 07/50', 'Estúdio', 'Autoridade, postura de liderança e olhar focado.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 08/50', 'Estúdio', 'Elegância dramática com forte contraste e seriedade.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 09/50', 'Estúdio', 'Conexão direta, simpatia e comunicação assertiva.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 10/50', 'Estúdio', 'Charme silencioso e atitude pensativa em tom noir.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 11/50', 'Estúdio', 'Polidez moderna e presença assertiva.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 12/50', 'Estúdio', 'Minimalismo dramático com foco intenso no olhar.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 13/50', 'Estúdio', 'Sofisticação moderna com postura relaxada e segura.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 14/50', 'Estúdio', 'Poder clássico, requinte e controle executivo.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 15/50', 'Estúdio', 'Visão estratégica e profissionalismo corporativo de alto nível.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 16/50', 'Estúdio', 'Mistério dominante, luxo e alta sofisticação executiva.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 17/50', 'Estúdio', 'Charme dinâmico e perfil altamente engajador.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 18/50', 'Estúdio', 'Proximidade inteligente com contraste profundo.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 19/50', 'Estúdio', 'Simplicidade editorial, clareza e intelectualidade.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 20/50', 'Estúdio', 'Ação, expressividade e domínio de palco.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');

-- MASCULINO - Cenário
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 21/50', 'Cenário', 'Desempenho premium em ambiente noturno de alto foco.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 22/50', 'Cenário', 'Rotina casual e produtiva em ambiente acolhedor.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 23/50', 'Cenário', 'Perspectiva visionária e foco nos negócios.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 24/50', 'Cenário', 'Contraste cru e textura urbana com aura de mistério.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 25/50', 'Cenário', 'Energia caótica da cidade equilibrada com luz dourada.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 26/50', 'Cenário', 'Triunfo majestoso com escala urbana e requinte.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 27/50', 'Cenário', 'Intelecto afiado, tradição e força profissional.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 28/50', 'Cenário', 'Estilo relaxado, urbano e editorial moderno.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 29/50', 'Cenário', 'Noir cinematográfico evocativo com ritmo fantasmagórico urbano.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 30/50', 'Cenário', 'Estética europeia sofisticada com elegância misteriosa.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 31/50', 'Cenário', 'Sucesso moderno e acessibilidade em lounge contemporâneo.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 32/50', 'Cenário', 'Elegância urbana, ambição e sofisticação casual.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 33/50', 'Cenário', 'Espírito explorador, dinamismo urbano e luz dourada.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 34/50', 'Cenário', 'Carisma acessível com atitude levemente rebelde.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 35/50', 'Cenário', 'Presença cinematográfica dramática com perspectiva imersiva.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 36/50', 'Cenário', 'Estética urbana com toque rústico e estilo vintage autêntico.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 37/50', 'Cenário', 'Energia lúdica, assertiva e estética de moda vanguardista.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 38/50', 'Cenário', 'Confiança ágil e estética streetwear de alto padrão.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 39/50', 'Cenário', 'Abordagem natural, relaxada, acolhedora e intelectual.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 40/50', 'Cenário', 'Presença enigmática e ousada em atmosfera industrial.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');

-- MASCULINO - Lifestyle
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Lifestyle URBANO', 'Lifestyle', 'Estilo urbano moderno com atitude e sofisticação em cenário de metrópole.', 'Masculino', 'Prefira roupas lisas, jaquetas, camadas ou acessórios urbanos. Evite estampas muito chamativas para um resultado mais elegante.', '/lifestyleurbano.png');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Lifestyle 42/50', 'Lifestyle', 'Aura clássica rebelde e estética vibrante de atitude.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Lifestyle 43/50', 'Lifestyle', 'Liderança majestosa e controle com contraste monocromático dramático.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Lifestyle 44/50', 'Lifestyle', 'Intensidade misteriosa com iluminação e sombras profundas.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Lifestyle 45/50', 'Lifestyle', 'Sofisticação contemporânea e conforto em ambiente luxuoso.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Lifestyle 46/50', 'Lifestyle', 'Grandeza executiva, autoridade inquestionável e poder clássico.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Lifestyle 47/50', 'Lifestyle', 'Criatividade envolvente e vibração de nômade digital produtivo.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Lifestyle 48/50', 'Lifestyle', 'Confiança rústica, simpatia genuína e calor humano autêntico.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Lifestyle 49/50', 'Lifestyle', 'Elegância contemporânea, carisma e sucesso sem esforço.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Lifestyle 50/50', 'Lifestyle', 'Visão futurista, postura imponente e determinação corporativa.', 'Masculino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');

-- FEMININO - Estúdio
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 01/50', 'Estúdio', 'Elegância minimalista, autoconfiança e poder sutil.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 02/50', 'Estúdio', 'Sofisticação moderna e feminilidade poderosa com contraste marcante.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 03/50', 'Estúdio', 'Entusiasmo, calor humano e dinamismo acolhedor.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 04/50', 'Estúdio', 'Energia vibrante, carisma expansivo e surpresa agradável.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 05/50', 'Estúdio', 'Liderança graciosa, profissionalismo e postura acessível.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 06/50', 'Estúdio', 'Dinamismo contemporâneo, confiança e apelo executivo moderno.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 07/50', 'Estúdio', 'Foco acadêmico, intelecto e postura analítica requintada.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 08/50', 'Estúdio', 'Cores vibrantes, calor radiante e dinamismo em apresentações.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 09/50', 'Estúdio', 'Poder brilhante, charme polido e estética calorosa.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 10/50', 'Estúdio', 'Força marcante, ousadia e liderança de estilo editorial.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 11/50', 'Estúdio', 'Postura reflexiva, inteligência sofisticada e beleza calma.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 12/50', 'Estúdio', 'Serenidade profissional, compostura e minimalismo chique.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 13/50', 'Estúdio', 'Empoderamento calmo e elegância estruturada em estética atemporal.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 14/50', 'Estúdio', 'Presença digital executiva com toque marcante e luxuoso.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 15/50', 'Estúdio', 'Clareza brilhante, simpatia envolvente e comunicação assertiva.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 16/50', 'Estúdio', 'Engajamento social ágil com sofisticação casual impecável.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 17/50', 'Estúdio', 'Aproximação relaxada, calor humano e integração com a tecnologia.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 18/50', 'Estúdio', 'Aura intelectual profunda e centelha de inspiração criativa.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 19/50', 'Estúdio', 'Autoridade imponente, refinamento clássico e luxo monocromático.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Estúdio 20/50', 'Estúdio', 'Elegância vibrante, contraste acolhedor e charme motivacional.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');

-- FEMININO - Cenário
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 21/50', 'Cenário', 'Conforto luminoso, intimidade e graciosidade executiva.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 22/50', 'Cenário', 'Liderança inspiradora com forte conexão à luz urbana.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 23/50', 'Cenário', 'Alegria radiante, leveza e confiança em ambiente empreendedor.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 24/50', 'Cenário', 'Refinamento aconchegante e postura profissional convidativa.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 25/50', 'Cenário', 'Foco produtivo apaixonado com charme acolhedor de cafeteria.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 26/50', 'Cenário', 'Comunicação digital moderna com leveza, carisma e clareza.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 27/50', 'Cenário', 'Poder carismático formidável e ambiente de luxo imponente.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 28/50', 'Cenário', 'Beleza atemporal, sofisticação vintage e postura serena.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 29/50', 'Cenário', 'Elegância aconchegante iluminada por tons requintados e suaves.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 30/50', 'Cenário', 'Dinamismo executivo multi-tarefa com estilo de alto padrão.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 31/50', 'Cenário', 'Decisão vibrante, estilo refinado e ambiente intelectual acolhedor.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 32/50', 'Cenário', 'Poder minimalista, atitude e clareza estética de alta moda.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 33/50', 'Cenário', 'Presença forte e dominante em ambiente de negócios afiado.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 34/50', 'Cenário', 'Liderança polida, foco apurado e produtividade empoderada.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 35/50', 'Cenário', 'Charme glamoroso, requinte exclusivo e brilho intimista caloroso.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 36/50', 'Cenário', 'Graciosidade imponente e poder refinado de alta classe.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 37/50', 'Cenário', 'Simpatia calorosa, harmonia de tons e estética de negócios suave.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 38/50', 'Cenário', 'Moda corporativa chique iluminada de forma dourada e convidativa.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 39/50', 'Cenário', 'Foco produtivo elegante adornado com toques de delicadeza romântica.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Cenário 40/50', 'Cenário', 'Sofisticação corporativa de altíssimo nível com brilho executivo cinematográfico.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');

-- FEMININO - Lifestyle
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Lifestyle URBANO', 'Lifestyle', 'Estilo urbano moderno com atitude e sofisticação em cenário de metrópole.', 'Feminino', 'Prefira roupas lisas, jaquetas, camadas ou acessórios urbanos. Evite estampas muito chamativas para um resultado mais elegante.', '/lifestyleurbano.png');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Lifestyle 42/50', 'Lifestyle', 'Introspecção enigmática, charme analítico e iluminação dramática.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Lifestyle 43/50', 'Lifestyle', 'Inteligência competitiva e liderança acentuada com contraste rústico.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Lifestyle 44/50', 'Lifestyle', 'Determinação calculada, intelecto profundo e atmosfera sombria.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Lifestyle 45/50', 'Lifestyle', 'Alegria vibrante, energia leve e casualidade fashionista colorida.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Lifestyle 46/50', 'Lifestyle', 'Poder luminoso, moda destemida e vida urbana noturna eletrizante.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Lifestyle 47/50', 'Lifestyle', 'Liberdade casual, energia descontraída e positividade em movimento.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Lifestyle 48/50', 'Lifestyle', 'Charme editorial arrojado, ousadia pura e carisma imbatível.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Lifestyle 49/50', 'Lifestyle', 'Mistério magnético e intenso foco estético com luxo pontual.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
INSERT INTO public.estilos (titulo, categoria, descricao, genero, dica_roupa, img_url) VALUES ('Lifestyle 50/50', 'Lifestyle', 'Magia conceitual, controle lúdico e elegância luxuosa flutuante.', 'Feminino', 'Prefira roupas lisas, blazers ou camisas de cores neutras. Evite estampas muito chamativas para um resultado mais elegante com a IA.', '');
